### ISSUE TITLE
из HA

### ISSUE THREAD

**Issue by krisproger** [turbulator/pandora-cas#19]
```
Регистратор: pandora_cas.account
Источник: /usr/local/lib/python3.12/site-packages/pandora_cas/account.py:1183
Первое сообщение: 1 сентября 2024 г. в 09:24:28 (52 сообщений)
Последнее сообщение: 13:58:37

[4232a5] Error during preliminary response processing with message type event: KeyError('event-name-167') Please, report this error to the developer immediately!
[4232a5] Error during preliminary response processing with message type event: KeyError('event-name-166') Please, report this error to the developer immediately!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pandora_cas/account.py", line 1173, in _handle_ws_message
    callback_coro = event_callback(device, result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pandora_cas/__init__.py", line 668, in _handle_ws_event
    else get_web_translations_value(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pandora_cas/translations.py", line 48, in get_web_translations_value
    return web_translations[language][key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'event-name-167'
```

**Comment by turbulator** [comment]
Дружище, у меня даже файла такого нету. Тебе вот сюда: https://github.com/alryaz/hass-pandora-cas/issues
